services:
  db:
    build:
      context: ./PostgresDoker
      dockerfile: Dockerfile
    container_name: magneto_vector_db
    environment:
      POSTGRES_DB: magneto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: magneto_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
